---
title: Minecraft Selfies
hero_image: images/banner.png
description: Make a selfie wall in Minecraft with Python
original_url: https://raspberrypi.org/learning/minecraft-selfies
theme: blue
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: 3, design-0, programming-3, phys-comp-2, manufacture-0, community-0
interests: photography
technologies: raspberry-pi, python, pi-camera
site_areas: projects
hardware: raspberry-pi, pi-camera
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
- title: What you will need
  completion: engaged
- title: Minecraft Selfies
- title: Importing some modules
- title: Taking a selfie
- title: Mapping colours to blocks
- title: Finding the nearest colour
- title: Converting to Lab colour space
- title: Mapping the blocks
- title: Starting the Minecraft API
- title: A better (but slower) algorithm
- title: What it looks like in RGB colour space
  completion: internal
- title: The full code
- title: What next?
